apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-worker
data:
  MOVIES_BUCKET_NAME: "testmovies4444"
  MOVIES_DB_USER: "root"
  MOVIES_DB_HOST: "mysql"
  MOVIES_DB_PORT: "3306"
  MOVIES_DB_NAME: "movies"
