#!/usr/bin/env bash
############################
# Script to run the worker #
############################
[ "${DEBUG}" = "1" ] && set -x
set -eEuo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

python3 "${SCRIPT_DIR}/../run_worker.py"
